title: GIA Wiki
author: Grupo de Ingeniería Aeroespacial
email: andres.cuberosalas@ucr.ac.cr
description: > # this means to ignore newlines until "baseurl:"
  Esta página contiene la completa documentación de las actividades y
  los proyectos realizados por el Grupo de Ingeniería Aeroespacial de la
  Universidad de Costa Rica y sus colaboradores.
  
theme: minima

# social links
instagram_username: giaucr # DO NOT include the @ character, or else the build will fail!
github_username:  giaucr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
